### PR TITLE
links to proposals, little copy shuffles

### PR DESCRIPTION
**Pull request by kissane**

### CODE REVIEW

**Comment by sinker** [comment]
does this PR supersede #70 or compliment it? should I be merging both or just this?

**Comment by kissane** [comment]
I don't know how that works. This includes @ryanpitts's changes, but IDK.

**Comment by sinker** [comment]
OK, so if it includes them, then we can kill that PR I think, though will wait for @ryanpitts to confirm and will merge this in the interim.

**Comment by ryanpitts** [comment]
ohhhh, @kissane are you working from a forked repo?

**Comment by ryanpitts** [comment]
yes, #70 still needs to be merged.

This PR merged changes from @kissane's fork of the `add-proposals-page` branch into the main repo's `add-proposals-page` branch. If you look at the commits listed in #70, you can see the updates there.

But nothing has hit `gh-pages` yet. #70 is a PR that takes changes from `add-proposals-page` and merges them into `gh-pages`.

**Pull request merged**
